error resolution by struts-spring-plugin add OK
http://localhost:9302/strutsSpring/ OK
but not http://localhost:9302/strutsSpring/index

févr. 15, 2018 10:37:39 PM
org.apache.tomcat.util.digester.SetPropertiesRule begin
AVERTISSEMENT: [SetPropertiesRule]{Server/Service/Engine/Host/Context}
Setting property 'source' to 'org.eclipse.jst.j2ee.server:strutsSpring'
did not find a matching property.
févr. 15, 2018 10:37:39 PM
org.apache.catalina.startup.VersionLoggerListener log
INFOS: Server version:        Apache Tomcat/8.0.36
févr. 15, 2018 10:37:39 PM
org.apache.catalina.startup.VersionLoggerListener log
INFOS: Server built:          Jun 9 2016 13:55:50 UTC
févr. 15, 2018 10:37:39 PM
org.apache.catalina.startup.VersionLoggerListener log
INFOS: Server number:         8.0.36.0
févr. 15, 2018 10:37:39 PM
org.apache.catalina.startup.VersionLoggerListener log
INFOS: OS Name:               Windows 10
févr. 15, 2018 10:37:39 PM
org.apache.catalina.startup.VersionLoggerListener log
INFOS: OS Version:            10.0
févr. 15, 2018 10:37:39 PM
org.apache.catalina.startup.VersionLoggerListener log
INFOS: Architecture:          amd64
févr. 15, 2018 10:37:39 PM
org.apache.catalina.startup.VersionLoggerListener log
INFOS: Java Home:             C:\Program Files\Java\jre1.8.0_151
févr. 15, 2018 10:37:39 PM
org.apache.catalina.startup.VersionLoggerListener log
INFOS: JVM Version:           1.8.0_151-b12
févr. 15, 2018 10:37:39 PM
org.apache.catalina.startup.VersionLoggerListener log
INFOS: JVM Vendor:            Oracle Corporation
févr. 15, 2018 10:37:39 PM
org.apache.catalina.startup.VersionLoggerListener log
INFOS: CATALINA_BASE:
C:\Users\mouez\workspace2\.metadata\.plugins\org.eclipse.wst.server.core\tmp0
févr. 15, 2018 10:37:39 PM
org.apache.catalina.startup.VersionLoggerListener log
INFOS: CATALINA_HOME:         C:\Users\mouez
févr. 15, 2018 10:37:39 PM
org.apache.catalina.startup.VersionLoggerListener log
INFOS: Command line argument:
-Dcatalina.base=C:\Users\mouez\workspace2\.metadata\.plugins\org.eclipse.wst.server.core\tmp0
févr. 15, 2018 10:37:39 PM
org.apache.catalina.startup.VersionLoggerListener log
INFOS: Command line argument: -Dcatalina.home=C:\Users\mouez
févr. 15, 2018 10:37:39 PM
org.apache.catalina.startup.VersionLoggerListener log
INFOS: Command line argument:
-Dwtp.deploy=C:\Users\mouez\workspace2\.metadata\.plugins\org.eclipse.wst.server.core\tmp0\wtpwebapps
févr. 15, 2018 10:37:39 PM
org.apache.catalina.startup.VersionLoggerListener log
INFOS: Command line argument:
-Djava.endorsed.dirs=C:\Users\mouez\endorsed
févr. 15, 2018 10:37:39 PM
org.apache.catalina.startup.VersionLoggerListener log
INFOS: Command line argument: -Dfile.encoding=Cp1252
févr. 15, 2018 10:37:39 PM org.apache.catalina.core.AprLifecycleListener
lifecycleEvent
INFOS: The APR based Apache Tomcat Native library which allows optimal
performance in production environments was not found on the
java.library.path: C:\Program
Files\Java\jre1.8.0_151\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program
Files\Git\cmd;C:\Program Files (x86)\Subversion\bin;C:\Program
Files\PuTTY\;C:\Program Files (x86)\Symantec\VIP Access
Client\;C:\Users\mouez\AppData\Local\Microsoft\WindowsApps;;.
févr. 15, 2018 10:37:39 PM org.apache.coyote.AbstractProtocol init
INFOS: Initializing ProtocolHandler ["http-nio-9302"]
févr. 15, 2018 10:37:40 PM org.apache.tomcat.util.net.NioSelectorPool
getSharedSelector
INFOS: Using a shared selector for servlet write/read
févr. 15, 2018 10:37:40 PM org.apache.coyote.AbstractProtocol init
INFOS: Initializing ProtocolHandler ["ajp-nio-8009"]
févr. 15, 2018 10:37:40 PM org.apache.tomcat.util.net.NioSelectorPool
getSharedSelector
INFOS: Using a shared selector for servlet write/read
févr. 15, 2018 10:37:40 PM org.apache.catalina.startup.Catalina load
INFOS: Initialization processed in 2970 ms
févr. 15, 2018 10:37:40 PM org.apache.catalina.core.StandardService
startInternal
INFOS: Démarrage du service Catalina
févr. 15, 2018 10:37:40 PM org.apache.catalina.core.StandardEngine
startInternal
INFOS: Starting Servlet Engine: Apache Tomcat/8.0.36
févr. 15, 2018 10:37:54 PM org.apache.jasper.servlet.TldScanner scanJars
INFOS: At least one JAR was scanned for TLDs yet contained no TLDs.
Enable debug logging for this logger for a complete list of JARs that
were scanned but no TLDs were found in them. Skipping unneeded JARs
during scanning can improve startup time and JSP compilation time.
févr. 15, 2018 10:38:11 PM org.apache.jasper.servlet.TldScanner scanJars
INFOS: At least one JAR was scanned for TLDs yet contained no TLDs.
Enable debug logging for this logger for a complete list of JARs that
were scanned but no TLDs were found in them. Skipping unneeded JARs
during scanning can improve startup time and JSP compilation time.
févr. 15, 2018 10:38:11 PM org.apache.catalina.core.ApplicationContext
log
INFOS: No Spring WebApplicationInitializer types detected on classpath
févr. 15, 2018 10:38:11 PM org.apache.catalina.core.ApplicationContext
log
INFOS: Initializing Spring root WebApplicationContext
févr. 15, 2018 10:38:11 PM org.springframework.web.context.ContextLoader
initWebApplicationContext
INFOS: Root WebApplicationContext: initialization started
févr. 15, 2018 10:38:12 PM
org.springframework.web.context.support.XmlWebApplicationContext
prepareRefresh
INFOS: Refreshing Root WebApplicationContext: startup date [Thu Feb 15
22:38:12 CET 2018]; root of context hierarchy
févr. 15, 2018 10:38:12 PM
org.springframework.beans.factory.xml.XmlBeanDefinitionReader
loadBeanDefinitions
INFOS: Loading XML bean definitions from ServletContext resource
[/WEB-INF/applicationContext.xml]
févr. 15, 2018 10:38:14 PM org.springframework.web.context.ContextLoader
initWebApplicationContext
INFOS: Root WebApplicationContext: initialization completed in 2799 ms
22:38:17.755 [localhost-startStop-1] ERROR
org.apache.struts2.dispatcher.Dispatcher - Dispatcher initialization
failed
com.opensymphony.xwork2.config.ConfigurationException: Unable to load
configuration.
	at com.opensymphony.xwork2.config.ConfigurationManager.getConfiguration(ConfigurationManager.java:69)
~[struts2-core-2.5.14.1.jar:2.5.14.1]
	at org.apache.struts2.dispatcher.Dispatcher.getContainer(Dispatcher.java:957)
~[struts2-core-2.5.14.1.jar:2.5.14.1]
	at org.apache.struts2.dispatcher.Dispatcher.init_PreloadConfiguration(Dispatcher.java:463)
~[struts2-core-2.5.14.1.jar:2.5.14.1]
	at org.apache.struts2.dispatcher.Dispatcher.init(Dispatcher.java:496)
[struts2-core-2.5.14.1.jar:2.5.14.1]
	at org.apache.struts2.dispatcher.InitOperations.initDispatcher(InitOperations.java:73)
[struts2-core-2.5.14.1.jar:2.5.14.1]
	at org.apache.struts2.dispatcher.filter.StrutsPrepareAndExecuteFilter.init(StrutsPrepareAndExecuteFilter.java:61)
[struts2-core-2.5.14.1.jar:2.5.14.1]
	at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:279)
[catalina.jar:8.0.36]
	at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:260)
[catalina.jar:8.0.36]
	at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:105)
[catalina.jar:8.0.36]
	at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4689)
[catalina.jar:8.0.36]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5329)
[catalina.jar:8.0.36]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
[catalina.jar:8.0.36]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1407)
[catalina.jar:8.0.36]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1397)
[catalina.jar:8.0.36]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[?:1.8.0_151]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
Caused by: com.opensymphony.xwork2.config.ConfigurationException: Cannot
locate the chosen ObjectFactory implementation: spring
	at org.apache.struts2.config.AbstractBeanSelectionProvider.alias(AbstractBeanSelectionProvider.java:82)
~[struts2-core-2.5.14.1.jar:2.5.14.1]
	at org.apache.struts2.config.AbstractBeanSelectionProvider.alias(AbstractBeanSelectionProvider.java:59)
~[struts2-core-2.5.14.1.jar:2.5.14.1]
	at org.apache.struts2.config.DefaultBeanSelectionProvider.register(DefaultBeanSelectionProvider.java:374)
~[struts2-core-2.5.14.1.jar:2.5.14.1]
	at com.opensymphony.xwork2.config.impl.DefaultConfiguration.reloadContainer(DefaultConfiguration.java:167)
~[struts2-core-2.5.14.1.jar:2.5.14.1]
	at com.opensymphony.xwork2.config.ConfigurationManager.getConfiguration(ConfigurationManager.java:66)
~[struts2-core-2.5.14.1.jar:2.5.14.1]
	... 17 more
févr. 15, 2018 10:38:17 PM org.apache.catalina.core.StandardContext
filterStart
GRAVE: Exception au démarrage du filtre struts2
Unable to load configuration. - [unknown location]
	at org.apache.struts2.dispatcher.Dispatcher.init(Dispatcher.java:509)
	at org.apache.struts2.dispatcher.InitOperations.initDispatcher(InitOperations.java:73)
	at org.apache.struts2.dispatcher.filter.StrutsPrepareAndExecuteFilter.init(StrutsPrepareAndExecuteFilter.java:61)
	at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:279)
	at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:260)
	at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:105)
	at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4689)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5329)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1407)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1397)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: Unable to load configuration. - [unknown location]
	at com.opensymphony.xwork2.config.ConfigurationManager.getConfiguration(ConfigurationManager.java:69)
	at org.apache.struts2.dispatcher.Dispatcher.getContainer(Dispatcher.java:957)
	at org.apache.struts2.dispatcher.Dispatcher.init_PreloadConfiguration(Dispatcher.java:463)
	at org.apache.struts2.dispatcher.Dispatcher.init(Dispatcher.java:496)
	... 14 more
Caused by: Cannot locate the chosen ObjectFactory implementation: spring
- [unknown location]
	at org.apache.struts2.config.AbstractBeanSelectionProvider.alias(AbstractBeanSelectionProvider.java:82)
	at org.apache.struts2.config.AbstractBeanSelectionProvider.alias(AbstractBeanSelectionProvider.java:59)
	at org.apache.struts2.config.DefaultBeanSelectionProvider.register(DefaultBeanSelectionProvider.java:374)
	at com.opensymphony.xwork2.config.impl.DefaultConfiguration.reloadContainer(DefaultConfiguration.java:167)
	at com.opensymphony.xwork2.config.ConfigurationManager.getConfiguration(ConfigurationManager.java:66)
	... 17 more

févr. 15, 2018 10:38:17 PM org.apache.catalina.core.StandardContext
startInternal
GRAVE: One or more Filters failed to start. Full details will be found
in the appropriate container log file
févr. 15, 2018 10:38:17 PM org.apache.catalina.core.StandardContext
startInternal
GRAVE: Erreur de démarrage du contexte [/strutsSpring] suite aux erreurs
précédentes
févr. 15, 2018 10:38:17 PM org.apache.catalina.core.ApplicationContext
log
INFOS: Closing Spring root WebApplicationContext
févr. 15, 2018 10:38:17 PM
org.springframework.web.context.support.XmlWebApplicationContext doClose
INFOS: Closing Root WebApplicationContext: startup date [Thu Feb 15
22:38:12 CET 2018]; root of context hierarchy
févr. 15, 2018 10:38:17 PM org.apache.coyote.AbstractProtocol start
INFOS: Starting ProtocolHandler ["http-nio-9302"]
févr. 15, 2018 10:38:18 PM org.apache.coyote.AbstractProtocol start
INFOS: Starting ProtocolHandler ["ajp-nio-8009"]
févr. 15, 2018 10:38:18 PM org.apache.catalina.startup.Catalina start
INFOS: Server startup in 37695 ms