log4j2.xml
against (inspired by https://github.com/hazelcast/hazelcast/issues/12058
)
févr. 15, 2018 4:48:16 PM
org.apache.tomcat.util.digester.SetPropertiesRule begin
AVERTISSEMENT: [SetPropertiesRule]{Server/Service/Engine/Host/Context}
Setting property 'source' to 'org.eclipse.jst.j2ee.server:strutsSpring'
did not find a matching property.
févr. 15, 2018 4:48:16 PM
org.apache.catalina.startup.VersionLoggerListener log
INFOS: Server version:        Apache Tomcat/8.0.36
févr. 15, 2018 4:48:16 PM
org.apache.catalina.startup.VersionLoggerListener log
INFOS: Server built:          Jun 9 2016 13:55:50 UTC
févr. 15, 2018 4:48:16 PM
org.apache.catalina.startup.VersionLoggerListener log
INFOS: Server number:         8.0.36.0
févr. 15, 2018 4:48:16 PM
org.apache.catalina.startup.VersionLoggerListener log
INFOS: OS Name:               Windows 10
févr. 15, 2018 4:48:16 PM
org.apache.catalina.startup.VersionLoggerListener log
INFOS: OS Version:            10.0
févr. 15, 2018 4:48:16 PM
org.apache.catalina.startup.VersionLoggerListener log
INFOS: Architecture:          amd64
févr. 15, 2018 4:48:16 PM
org.apache.catalina.startup.VersionLoggerListener log
INFOS: Java Home:             C:\Program Files\Java\jre1.8.0_151
févr. 15, 2018 4:48:16 PM
org.apache.catalina.startup.VersionLoggerListener log
INFOS: JVM Version:           1.8.0_151-b12
févr. 15, 2018 4:48:16 PM
org.apache.catalina.startup.VersionLoggerListener log
INFOS: JVM Vendor:            Oracle Corporation
févr. 15, 2018 4:48:16 PM
org.apache.catalina.startup.VersionLoggerListener log
INFOS: CATALINA_BASE:
C:\Users\mouez\workspace2\.metadata\.plugins\org.eclipse.wst.server.core\tmp0
févr. 15, 2018 4:48:16 PM
org.apache.catalina.startup.VersionLoggerListener log
INFOS: CATALINA_HOME:         C:\Users\mouez
févr. 15, 2018 4:48:16 PM
org.apache.catalina.startup.VersionLoggerListener log
INFOS: Command line argument:
-agentlib:jdwp=transport=dt_socket,suspend=y,address=localhost:51390
févr. 15, 2018 4:48:16 PM
org.apache.catalina.startup.VersionLoggerListener log
INFOS: Command line argument:
-Dcatalina.base=C:\Users\mouez\workspace2\.metadata\.plugins\org.eclipse.wst.server.core\tmp0
févr. 15, 2018 4:48:16 PM
org.apache.catalina.startup.VersionLoggerListener log
INFOS: Command line argument: -Dcatalina.home=C:\Users\mouez
févr. 15, 2018 4:48:16 PM
org.apache.catalina.startup.VersionLoggerListener log
INFOS: Command line argument:
-Dwtp.deploy=C:\Users\mouez\workspace2\.metadata\.plugins\org.eclipse.wst.server.core\tmp0\wtpwebapps
févr. 15, 2018 4:48:16 PM
org.apache.catalina.startup.VersionLoggerListener log
INFOS: Command line argument:
-Djava.endorsed.dirs=C:\Users\mouez\endorsed
févr. 15, 2018 4:48:16 PM
org.apache.catalina.startup.VersionLoggerListener log
INFOS: Command line argument: -Dfile.encoding=Cp1252
févr. 15, 2018 4:48:16 PM org.apache.catalina.core.AprLifecycleListener
lifecycleEvent
INFOS: The APR based Apache Tomcat Native library which allows optimal
performance in production environments was not found on the
java.library.path: C:\Program
Files\Java\jre1.8.0_151\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program
Files\Git\cmd;C:\Program Files (x86)\Subversion\bin;C:\Program
Files\PuTTY\;C:\Program Files (x86)\Symantec\VIP Access
Client\;C:\Users\mouez\AppData\Local\Microsoft\WindowsApps;;.
févr. 15, 2018 4:48:16 PM org.apache.coyote.AbstractProtocol init
INFOS: Initializing ProtocolHandler ["http-nio-9302"]
févr. 15, 2018 4:48:17 PM org.apache.tomcat.util.net.NioSelectorPool
getSharedSelector
INFOS: Using a shared selector for servlet write/read
févr. 15, 2018 4:48:17 PM org.apache.coyote.AbstractProtocol init
INFOS: Initializing ProtocolHandler ["ajp-nio-8009"]
févr. 15, 2018 4:48:17 PM org.apache.tomcat.util.net.NioSelectorPool
getSharedSelector
INFOS: Using a shared selector for servlet write/read
févr. 15, 2018 4:48:17 PM org.apache.catalina.startup.Catalina load
INFOS: Initialization processed in 2913 ms
févr. 15, 2018 4:48:17 PM org.apache.catalina.core.StandardService
startInternal
INFOS: Démarrage du service Catalina
févr. 15, 2018 4:48:17 PM org.apache.catalina.core.StandardEngine
startInternal
INFOS: Starting Servlet Engine: Apache Tomcat/8.0.36
févr. 15, 2018 4:48:30 PM org.apache.jasper.servlet.TldScanner scanJars
INFOS: At least one JAR was scanned for TLDs yet contained no TLDs.
Enable debug logging for this logger for a complete list of JARs that
were scanned but no TLDs were found in them. Skipping unneeded JARs
during scanning can improve startup time and JSP compilation time.
févr. 15, 2018 4:48:48 PM org.apache.jasper.servlet.TldScanner scanJars
INFOS: At least one JAR was scanned for TLDs yet contained no TLDs.
Enable debug logging for this logger for a complete list of JARs that
were scanned but no TLDs were found in them. Skipping unneeded JARs
during scanning can improve startup time and JSP compilation time.
févr. 15, 2018 4:48:48 PM org.apache.catalina.core.ApplicationContext
log
INFOS: No Spring WebApplicationInitializer types detected on classpath
févr. 15, 2018 4:48:48 PM org.apache.catalina.core.ApplicationContext
log
INFOS: Initializing Spring root WebApplicationContext
févr. 15, 2018 4:48:48 PM org.springframework.web.context.ContextLoader
initWebApplicationContext
INFOS: Root WebApplicationContext: initialization started
févr. 15, 2018 4:48:49 PM
org.springframework.web.context.support.XmlWebApplicationContext
prepareRefresh
INFOS: Refreshing Root WebApplicationContext: startup date [Thu Feb 15
16:48:49 CET 2018]; root of context hierarchy
févr. 15, 2018 4:48:49 PM
org.springframework.beans.factory.xml.XmlBeanDefinitionReader
loadBeanDefinitions
INFOS: Loading XML bean definitions from ServletContext resource
[/WEB-INF/applicationContext.xml]
févr. 15, 2018 4:48:51 PM org.springframework.web.context.ContextLoader
initWebApplicationContext
INFOS: Root WebApplicationContext: initialization completed in 2782 ms
ERROR StatusLogger No log4j2 configuration file found. Using default
configuration: logging only errors to the console. Set system property
'log4j2.debug' to show Log4j2 internal initialization logging.
févr. 15, 2018 4:48:54 PM org.apache.catalina.core.StandardContext
filterStart
GRAVE: Exception au démarrage du filtre struts2
java.lang.NoClassDefFoundError:
org/apache/logging/log4j/util/MultiFormatStringBuilderFormattable
	at org.apache.logging.log4j.core.pattern.MessagePatternConverter.format(MessagePatternConverter.java:120)
	at org.apache.logging.log4j.core.pattern.PatternFormatter.format(PatternFormatter.java:38)
	at org.apache.logging.log4j.core.layout.PatternLayout$PatternSerializer.toSerializable(PatternLayout.java:334)
	at org.apache.logging.log4j.core.layout.PatternLayout.toText(PatternLayout.java:233)
	at org.apache.logging.log4j.core.layout.PatternLayout.encode(PatternLayout.java:218)
	at org.apache.logging.log4j.core.layout.PatternLayout.encode(PatternLayout.java:58)
	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.directEncodeEvent(AbstractOutputStreamAppender.java:177)
	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.tryAppend(AbstractOutputStreamAppender.java:170)
	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:161)
	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:129)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84)
	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:448)
	at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:433)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:417)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:403)
	at org.apache.logging.log4j.core.config.DefaultReliabilityStrategy.log(DefaultReliabilityStrategy.java:49)
	at org.apache.logging.log4j.core.Logger.logMessage(Logger.java:146)
	at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2116)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2100)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2035)
	at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1914)
	at org.apache.logging.log4j.spi.AbstractLogger.error(AbstractLogger.java:876)
	at com.opensymphony.xwork2.util.DomHelper$StartHandler.error(DomHelper.java:366)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(Unknown
Source)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown
Source)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown
Source)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown
Source)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown
Source)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl$NSContentDriver.scanRootElementHook(Unknown
Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown
Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(Unknown
Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown
Source)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(Unknown
Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown
Source)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown
Source)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown
Source)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown
Source)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown
Source)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown
Source)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(Unknown
Source)
	at com.opensymphony.xwork2.util.DomHelper.parse(DomHelper.java:118)
	at com.opensymphony.xwork2.config.providers.XmlConfigurationProvider.loadConfigurationFiles(XmlConfigurationProvider.java:1060)
	at com.opensymphony.xwork2.config.providers.XmlConfigurationProvider.loadDocuments(XmlConfigurationProvider.java:198)
	at com.opensymphony.xwork2.config.providers.XmlConfigurationProvider.init(XmlConfigurationProvider.java:165)
	at com.opensymphony.xwork2.config.impl.DefaultConfiguration.reloadContainer(DefaultConfiguration.java:166)
	at com.opensymphony.xwork2.config.ConfigurationManager.getConfiguration(ConfigurationManager.java:66)
	at org.apache.struts2.dispatcher.Dispatcher.getContainer(Dispatcher.java:957)
	at org.apache.struts2.dispatcher.Dispatcher.init_PreloadConfiguration(Dispatcher.java:463)
	at org.apache.struts2.dispatcher.Dispatcher.init(Dispatcher.java:496)
	at org.apache.struts2.dispatcher.InitOperations.initDispatcher(InitOperations.java:73)
	at org.apache.struts2.dispatcher.filter.StrutsPrepareAndExecuteFilter.init(StrutsPrepareAndExecuteFilter.java:61)
	at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:279)
	at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:260)
	at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:105)
	at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4689)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5329)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1407)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1397)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException:
org.apache.logging.log4j.util.MultiFormatStringBuilderFormattable
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1332)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1166)
	... 65 more

févr. 15, 2018 4:48:54 PM org.apache.catalina.core.StandardContext
startInternal
GRAVE: One or more Filters failed to start. Full details will be found
in the appropriate container log file
févr. 15, 2018 4:48:54 PM org.apache.catalina.core.StandardContext
startInternal
GRAVE: Erreur de démarrage du contexte [/strutsSpring] suite aux erreurs
précédentes
févr. 15, 2018 4:48:54 PM org.apache.catalina.core.ApplicationContext
log
INFOS: Closing Spring root WebApplicationContext
févr. 15, 2018 4:48:54 PM
org.springframework.web.context.support.XmlWebApplicationContext doClose
INFOS: Closing Root WebApplicationContext: startup date [Thu Feb 15
16:48:49 CET 2018]; root of context hierarchy
févr. 15, 2018 4:48:54 PM org.apache.coyote.AbstractProtocol start
INFOS: Starting ProtocolHandler ["http-nio-9302"]
févr. 15, 2018 4:48:54 PM org.apache.coyote.AbstractProtocol start
INFOS: Starting ProtocolHandler ["ajp-nio-8009"]
févr. 15, 2018 4:48:55 PM org.apache.catalina.startup.Catalina start
INFOS: Server startup in 37671 ms